### ISSUE TITLE
Reenable /speakers view

### ISSUE THREAD

**Issue by TheFrankemon** [GDGCochabamba/devfestsite2016#54]
Update Firebase data about actual speakers and enable /speakers template

**Comment by diegosebgonz** [comment]
![image](https://user-images.githubusercontent.com/13753655/47878229-28bc7c00-ddf4-11e8-8000-594587b2d952.png)

**Comment by diegosebgonz** [comment]
![image](https://user-images.githubusercontent.com/13753655/47878319-5a354780-ddf4-11e8-826c-2e63ddc149d8.png)

**Comment by diegosebgonz** [comment]
Sent to **Code Review**!

PR -> https://github.com/GDGCochabamba/devfest-site/pull/55
CC: @TheFrankemon

**Comment by TheFrankemon** [comment]
At least today I had time on reviewing it, thanks again @diegosebgonz ! everything looks awesome, #55 fully merged 😃
