### ISSUE TITLE
Sections/functionality progress

### ISSUE THREAD

**Issue by ropilz** [GDGCochabamba/devfestsite2016#6]
Home Screen
--------------

- [x]  Summary
- [ ] Speakers
- [ ] Notifications
- [x] Featured videos (removed #10)
- [x] Organizer / What's GDG
- [x] News (removed #10)
- [x] Past events highlights
- [x] Tickets Pricing / availability #16
- [x] Location (updated #7)
- [ ] Partners

Blog
----

- [x] Blog entries - **not used**

Schedule
---------

- [ ] Schedule
- [ ] Tracks
- [ ] My Schedule

Speakers
---------

- [ ] Badges (GDG, GDE)
- [ ] Info

**Comment by TheFrankemon** [comment]
The following elements will be removed:
* Featured videos (we don't have enough videos :/)
* News (all of them will be posted in the Facebook page)

The following elements will be moved (by now 04/11):
* Notifications (sent to bottom > it's not useful for this actual event)
