### ISSUE TITLE
Gather information

### ISSUE THREAD

**Issue by ropilz** [GDGCochabamba/devfestsite2016#8]
- [x] Location - **UMSS**
- [x] Days - **November 25**
- [ ] Speakers - *Waiting for Lila team*
- [ ] Schedule - *Waiting for Lila team*
- [ ] Photos - *Waiting for Design team*
- [ ] Team info
- [x] Blog - **Not used**
- [ ] GDG contact links
- [x] Ticket price - **Not used**
- [ ] Text content
- [ ] Partners

**Comment by TheFrankemon** [comment]
Update 07/11
- [ ] Location > Lu is almost confirming UMSS
- [x] Days > Lu confirmed to be only one day (25/11)
- [ ] Speakers > Vania should send us the confirmed speakers pretty soon
- [ ] Schedule > Vania(?). Could be left until few days before the event
- [x] Photos > Discard (?)
- [x] Team info > Just updated by me (Minor changes would happen afterwards)
- [x] Blog > Discard (?)
- [ ] GDG contact links ??
